
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package sintactico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int T_PADME = 4;
  public static final int MENOS = 7;
  public static final int CADENA = 17;
  public static final int IGUAL = 11;
  public static final int PARIZQ = 13;
  public static final int T_ANAKI = 3;
  public static final int CONCAT = 10;
  public static final int PARDER = 14;
  public static final int ID = 18;
  public static final int POR = 8;
  public static final int EOF = 0;
  public static final int DIV = 9;
  public static final int error = 1;
  public static final int T_ABI = 2;
  public static final int ENTERO = 15;
  public static final int PCOMA = 12;
  public static final int T_IMPRIMIR = 5;
  public static final int MAS = 6;
  public static final int DOUBLE = 16;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "T_ABI",
  "T_ANAKI",
  "T_PADME",
  "T_IMPRIMIR",
  "MAS",
  "MENOS",
  "POR",
  "DIV",
  "CONCAT",
  "IGUAL",
  "PCOMA",
  "PARIZQ",
  "PARDER",
  "ENTERO",
  "DOUBLE",
  "CADENA",
  "ID"
  };
}

